sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.2
  matrix:
    - GW_MACHINE_NAME=raspberry-pi
    - GW_MACHINE_NAME=raspberrypi3

language: python
python: 3.6

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - pip install yq
  # Ensure we can build ARM images
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  # Use the .env template to provide defaults during build
  - cp .env-distr .env
  # Build images
  - docker-compose -f docker-compose-prometheus.yml build
  - docker-compose -f docker-compose-collectd.yml build

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy_docker.sh
  on:
    all_branches: true

jobs:
  include:
    - stage: balena
      name: "Deploy to balenaCloud"
      before_install: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: ./scripts/deploy_balena.sh
        on:
          all_branches: true

